//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PzProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GODZINY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GODZINY()
        {
            this.BILET = new HashSet<BILET>();
        }
    
        public int Id_Godziny { get; set; }
        public Nullable<int> Id_Seansu { get; set; }
        public string Godzina { get; set; }
        public string Miejsca { get; set; }
    
        public virtual SEANS SEANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILET> BILET { get; set; }
    }
}
