//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PzProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIEJSCE
    {
        public int id_miejsce { get; set; }
        public Nullable<int> rzad { get; set; }
        public Nullable<int> miejsce1 { get; set; }
        public bool zajete { get; set; }
        public int id_sala { get; set; }
    
        public virtual SALA SALA { get; set; }
    }
}
