//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PzProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEANS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEANS()
        {
            this.BILET = new HashSet<BILET>();
            this.GODZINY = new HashSet<GODZINY>();
        }
    
        public int Id_seans { get; set; }
        public Nullable<System.DateTime> Data_rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_zakonczenia { get; set; }
        public Nullable<int> Id_sala { get; set; }
        public Nullable<int> Id_film { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILET> BILET { get; set; }
        public virtual SALA SALA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GODZINY> GODZINY { get; set; }
    }
}
