//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PzProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEANS
    {
        public SEANS()
        {
            this.BILET = new HashSet<BILET>();
        }
    
        public int id_seans { get; set; }
        public Nullable<System.DateTime> dzien { get; set; }
        public Nullable<System.TimeSpan> godzina { get; set; }
        public int id_film { get; set; }
        public int id_gatunek { get; set; }
        public int id_sala { get; set; }
    
        public virtual ICollection<BILET> BILET { get; set; }
        public virtual FILM FILM { get; set; }
        public virtual SALA SALA { get; set; }
    }
}
