//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PzProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULGA
    {
        public ULGA()
        {
            this.BILET = new HashSet<BILET>();
        }
    
        public int id_ulga { get; set; }
        public Nullable<int> wartosc { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<BILET> BILET { get; set; }
    }
}
